# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to any branch. 
# For real use you might want to restrict this to the "prod" branch.
#

name: Deploy microservice

on:
  #
  # Deploys the microservice on push to the main branch of this code repository.
  #
  push: 
    branches:
      - main

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Builds the Docker image.
      #
      - name: Build
        run: ./scripts/build-image.sh

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: ./scripts/push-image.sh

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
          
      #
      # Checks and cleans the Kube config file to ensure it's valid.
      #
      - name: Check Kube Config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > /home/runner/.kube/config
          tr -cd '\11\12\15\40-\176' < /home/runner/.kube/config > /home/runner/.kube/config.cleaned
          mv /home/runner/.kube/config.cleaned /home/runner/.kube/config
          cat /home/runner/.kube/config  # Consider removing this line after debugging for security.

      #
      # Optional: Check Kube Config Validity
      #
      - name: Check Kube Config Validity
        run: |
          kubectl config view
          kubectl get nodes  # This checks if the config can connect to the cluster.

      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: ./scripts/deploy.sh
