name: Deploy microservice

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./scripts/build-image.sh

      - name: Publish
        run: ./scripts/push-image.sh

      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "Base64 input length: ${#KUBE_CONFIG}"  # Output the length for debugging
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          tr -cd '\11\12\15\40-\176' < $HOME/.kube/config > $HOME/.kube/config.cleaned
          mv $HOME/.kube/config.cleaned $HOME/.kube/config
      
      - name: Deploy
        run: ./scripts/deploy.sh
